language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.5
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
